# Generated by Django 4.0.2 on 2022-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45)),
                ('sitename', models.CharField(max_length=45)),
                ('siteaddress', models.CharField(max_length=200)),
                ('utillityname', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('emailaddress', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
